name: Minimal Android CI Workflow

on:
  workflow_dispatch:
    inputs:
        offerLink:
          type: string
          required: true
        packageId:
          type: string
          required: true
        versionName:
          type: string
          required: true
        versionCode:
          type: number
          required: true
        appName:
          type: string
          required: true
        iconUrl:
          type: string
          required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Prepare env
        run: |
          echo "versionCode=${{ github.event.inputs.versionCode }}" > local.properties
          echo "versionName=${{ github.event.inputs.versionName }}" >> local.properties
          echo "appName=${{ github.event.inputs.appName }}" >> local.properties
          echo "{\"offerLink\": \"${{ github.event.inputs.offerLink }}\"}" > app/src/main/assets/config.json
          find . -type f -exec sed -i 's/com.otherxample.testrename/${{ github.event.inputs.packageId }}/g' {} \;
          wget -O icon.png ${{ github.event.inputs.iconUrl }}
          find ./app/src -type f -name 'ic_launcher.*' | while read -r icon; do size=`convert "$icon" -print '%wx%h!' /dev/null`; cp icon.png "$icon" && convert "$icon" -resize "$size" "$icon"; done
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Auth GCloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDS }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Use gcloud CLI
        run: 'gcloud storage cp app/build/outputs/apk/release/app-release.apk gs://tictactoe-9681c.appspot.com/first.apk'
